-- Omarchy Monochrome Colorscheme
-- Pure black background with grayscale foreground

local M = {}

M.palette = {
  bg = "#000000",
  fg = "#C5C9C7",
  black = "#000000",
  gray_very_dark = "#1a1a1a",
  gray_dark = "#393B44",
  gray = "#75797F",
  gray_mid = "#888888",
  gray_light = "#999999",
  gray_lighter = "#bbbbbb",
  white = "#ffffff",
  cursor = "#C5C9C7",
  selection_bg = "#393B44",
  selection_fg = "#C5C9C7",
  line_nr = "#555555",
  line_nr_active = "#999999",
}

local function setup_highlights()
  local c = M.palette
  local h = vim.api.nvim_set_hl

  -- Editor basics
  h(0, "Normal", { bg = c.bg, fg = c.fg })
  h(0, "NormalFloat", { bg = c.black, fg = c.fg })
  h(0, "FloatBorder", { fg = c.gray_dark, bg = c.black })
  h(0, "Cursor", { bg = c.cursor, fg = c.bg })
  h(0, "CursorLine", { bg = c.gray_very_dark })
  h(0, "CursorLineNr", { fg = c.line_nr_active, bg = c.gray_very_dark, bold = true })
  h(0, "LineNr", { fg = c.line_nr, bg = c.bg })
  h(0, "ColorColumn", { bg = c.gray_very_dark })
  h(0, "SignColumn", { bg = c.bg })
  h(0, "Visual", { bg = c.selection_bg, fg = c.selection_fg })
  h(0, "VisualNOS", { bg = c.gray_dark })
  h(0, "Search", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "IncSearch", { bg = c.gray_light, fg = c.black, bold = true })
  h(0, "CurSearch", { bg = c.gray_lighter, fg = c.black, bold = true })
  h(0, "MatchParen", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "Whitespace", { fg = c.gray_dark })
  h(0, "NonText", { fg = c.gray_dark })
  h(0, "EndOfBuffer", { fg = c.gray_very_dark })
  h(0, "SpecialKey", { fg = c.gray })

  -- Status line / splits
  h(0, "StatusLine", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "StatusLineNC", { bg = c.black, fg = c.gray })
  h(0, "VertSplit", { fg = c.gray_dark })
  h(0, "WinSeparator", { fg = c.gray_dark })
  h(0, "Title", { fg = c.white, bold = true })

  -- Messages
  h(0, "ErrorMsg", { fg = c.gray_lighter, bg = c.black, bold = true })
  h(0, "WarningMsg", { fg = c.gray_light, bold = true })
  h(0, "MoreMsg", { fg = c.gray_lighter, bold = true })
  h(0, "ModeMsg", { fg = c.gray_lighter, bold = true })
  h(0, "Question", { fg = c.fg, bold = true })

  -- Menus / Pmenu
  h(0, "Pmenu", { bg = c.black, fg = c.fg })
  h(0, "PmenuSel", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "PmenuSbar", { bg = c.gray_very_dark })
  h(0, "PmenuThumb", { bg = c.gray })
  h(0, "WildMenu", { bg = c.gray_dark, fg = c.white })

  -- Folds / diffs
  h(0, "Folded", { bg = c.gray_very_dark, fg = c.gray_light })
  h(0, "FoldColumn", { fg = c.gray })
  h(0, "DiffAdd", { bg = c.gray_very_dark, fg = c.gray_lighter })
  h(0, "DiffChange", { bg = c.gray_very_dark, fg = c.gray_lighter })
  h(0, "DiffDelete", { bg = c.black, fg = c.gray_dark })
  h(0, "DiffText", { bg = c.gray_dark, fg = c.white, bold = true })

  -- Spelling
  h(0, "SpellBad", { undercurl = true, sp = c.gray_light })
  h(0, "SpellCap", { undercurl = true, sp = c.gray })
  h(0, "SpellRare", { undercurl = true, sp = c.gray_lighter })
  h(0, "SpellLocal", { undercurl = true, sp = c.gray_mid })

  -- Tabs
  h(0, "TabLine", { bg = c.black, fg = c.gray })
  h(0, "TabLineFill", { bg = c.bg })
  h(0, "TabLineSel", { bg = c.gray_dark, fg = c.white, bold = true })

  -- Syntax - Base (all grayscale)
  h(0, "Comment", { fg = c.gray, italic = true })
  h(0, "Constant", { fg = c.gray_lighter })
  h(0, "String", { fg = c.gray_lighter })
  h(0, "Character", { fg = c.gray_lighter })
  h(0, "Number", { fg = c.gray_light })
  h(0, "Boolean", { fg = c.gray_lighter, bold = true })
  h(0, "Float", { fg = c.gray_light })

  h(0, "Identifier", { fg = c.fg })
  h(0, "Function", { fg = c.white, bold = true })

  h(0, "Statement", { fg = c.gray_lighter, bold = true })
  h(0, "Conditional", { fg = c.gray_lighter, bold = true })
  h(0, "Repeat", { fg = c.gray_lighter, bold = true })
  h(0, "Label", { fg = c.gray_lighter, bold = true })
  h(0, "Operator", { fg = c.gray_light })
  h(0, "Keyword", { fg = c.gray_lighter, bold = true })
  h(0, "Exception", { fg = c.gray_lighter, bold = true })

  h(0, "PreProc", { fg = c.gray_light })
  h(0, "Include", { fg = c.gray_light })
  h(0, "Define", { fg = c.gray_light })
  h(0, "Macro", { fg = c.gray_light })
  h(0, "PreCondit", { fg = c.gray_light })

  h(0, "Type", { fg = c.gray_lighter })
  h(0, "StorageClass", { fg = c.gray_lighter })
  h(0, "Structure", { fg = c.gray_lighter })
  h(0, "Typedef", { fg = c.gray_lighter })

  h(0, "Special", { fg = c.gray_light })
  h(0, "SpecialChar", { fg = c.gray_light })
  h(0, "Tag", { fg = c.gray_light })
  h(0, "Delimiter", { fg = c.gray_mid })
  h(0, "SpecialComment", { fg = c.gray, italic = true, bold = true })
  h(0, "Debug", { fg = c.gray_lighter })

  h(0, "Underlined", { underline = true })
  h(0, "Bold", { bold = true })
  h(0, "Italic", { italic = true })
  h(0, "Ignore", { fg = c.gray_dark })
  h(0, "Error", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "Todo", { fg = c.white, bg = c.gray_dark, bold = true })

  -- Treesitter / LSP semantic highlights (map all to grayscale)
  h(0, "@variable", { fg = c.fg })
  h(0, "@variable.builtin", { fg = c.gray_light, italic = true })
  h(0, "@variable.parameter", { fg = c.gray_lighter })
  h(0, "@variable.member", { fg = c.fg })
  h(0, "@constant", { fg = c.gray_lighter })
  h(0, "@constant.builtin", { fg = c.gray_lighter, bold = true })
  h(0, "@constant.macro", { fg = c.gray_light })
  h(0, "@module", { fg = c.gray_lighter })
  h(0, "@module.builtin", { fg = c.gray_lighter, bold = true })
  h(0, "@label", { fg = c.gray_light })
  h(0, "@string", { fg = c.gray_lighter })
  h(0, "@string.documentation", { fg = c.gray, italic = true })
  h(0, "@string.regexp", { fg = c.gray_light })
  h(0, "@string.escape", { fg = c.gray_light, bold = true })
  h(0, "@string.special", { fg = c.gray_light })
  h(0, "@character", { fg = c.gray_lighter })
  h(0, "@character.special", { fg = c.gray_light })
  h(0, "@boolean", { fg = c.gray_lighter, bold = true })
  h(0, "@number", { fg = c.gray_light })
  h(0, "@number.float", { fg = c.gray_light })
  h(0, "@type", { fg = c.gray_lighter })
  h(0, "@type.builtin", { fg = c.gray_lighter, italic = true })
  h(0, "@type.definition", { fg = c.gray_lighter })
  h(0, "@attribute", { fg = c.gray_light })
  h(0, "@attribute.builtin", { fg = c.gray_light, italic = true })
  h(0, "@property", { fg = c.fg })
  h(0, "@function", { fg = c.white, bold = true })
  h(0, "@function.builtin", { fg = c.white, bold = true, italic = true })
  h(0, "@function.call", { fg = c.white, bold = true })
  h(0, "@function.macro", { fg = c.white, bold = true })
  h(0, "@function.method", { fg = c.white, bold = true })
  h(0, "@function.method.call", { fg = c.white, bold = true })
  h(0, "@constructor", { fg = c.gray_lighter })
  h(0, "@operator", { fg = c.gray_mid })
  h(0, "@keyword", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.coroutine", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.function", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.operator", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.import", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.type", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.modifier", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.repeat", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.return", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.debug", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.exception", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.conditional", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.conditional.ternary", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.directive", { fg = c.gray_lighter, bold = true })
  h(0, "@keyword.directive.define", { fg = c.gray_lighter, bold = true })
  h(0, "@punctuation.delimiter", { fg = c.gray_mid })
  h(0, "@punctuation.bracket", { fg = c.gray_mid })
  h(0, "@punctuation.special", { fg = c.gray_mid })
  h(0, "@comment", { fg = c.gray, italic = true })
  h(0, "@comment.documentation", { fg = c.gray, italic = true })
  h(0, "@comment.error", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "@comment.warning", { fg = c.black, bg = c.gray_light, bold = true })
  h(0, "@comment.todo", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "@comment.note", { fg = c.black, bg = c.gray_lighter, bold = true })
  h(0, "@tag", { fg = c.gray_lighter })
  h(0, "@tag.builtin", { fg = c.gray_lighter, italic = true })
  h(0, "@tag.attribute", { fg = c.fg })
  h(0, "@tag.delimiter", { fg = c.gray_mid })

  -- LSP
  h(0, "LspReferenceText", { bg = c.gray_dark })
  h(0, "LspReferenceRead", { bg = c.gray_dark })
  h(0, "LspReferenceWrite", { bg = c.gray_dark, underline = true })
  h(0, "LspSignatureActiveParameter", { bg = c.gray_dark, bold = true })
  h(0, "LspCodeLens", { fg = c.gray, italic = true })
  h(0, "LspInlayHint", { fg = c.gray_dark, bg = c.gray_very_dark })
  h(0, "LspInfoBorder", { fg = c.gray_dark })

  -- Diagnostics (grayscale)
  h(0, "DiagnosticError", { fg = c.gray_lighter, bold = true })
  h(0, "DiagnosticWarn", { fg = c.gray_light, bold = true })
  h(0, "DiagnosticInfo", { fg = c.gray })
  h(0, "DiagnosticHint", { fg = c.gray_dark })
  h(0, "DiagnosticOk", { fg = c.gray_lighter })
  h(0, "DiagnosticVirtualTextError", { fg = c.gray_light, bg = c.gray_very_dark })
  h(0, "DiagnosticVirtualTextWarn", { fg = c.gray, bg = c.gray_very_dark })
  h(0, "DiagnosticVirtualTextInfo", { fg = c.gray, bg = c.gray_very_dark })
  h(0, "DiagnosticVirtualTextHint", { fg = c.gray_dark, bg = c.gray_very_dark })
  h(0, "DiagnosticVirtualTextOk", { fg = c.gray_lighter, bg = c.gray_very_dark })
  h(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.gray_lighter })
  h(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.gray_light })
  h(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = c.gray })
  h(0, "DiagnosticUnderlineHint", { undercurl = true, sp = c.gray_dark })
  h(0, "DiagnosticUnderlineOk", { undercurl = true, sp = c.gray_lighter })
  h(0, "DiagnosticFloatingError", { fg = c.gray_lighter })
  h(0, "DiagnosticFloatingWarn", { fg = c.gray_light })
  h(0, "DiagnosticFloatingInfo", { fg = c.gray })
  h(0, "DiagnosticFloatingHint", { fg = c.gray_dark })
  h(0, "DiagnosticFloatingOk", { fg = c.gray_lighter })
  h(0, "DiagnosticSignError", { fg = c.gray_lighter })
  h(0, "DiagnosticSignWarn", { fg = c.gray_light })
  h(0, "DiagnosticSignInfo", { fg = c.gray })
  h(0, "DiagnosticSignHint", { fg = c.gray_dark })
  h(0, "DiagnosticSignOk", { fg = c.gray_lighter })

  -- Git (grayscale)
  h(0, "GitSignsAdd", { fg = c.gray_lighter })
  h(0, "GitSignsChange", { fg = c.gray_light })
  h(0, "GitSignsDelete", { fg = c.gray })
  h(0, "GitSignsAddNr", { fg = c.gray_lighter })
  h(0, "GitSignsChangeNr", { fg = c.gray_light })
  h(0, "GitSignsDeleteNr", { fg = c.gray })
  h(0, "GitSignsAddLn", { bg = c.gray_very_dark })
  h(0, "GitSignsChangeLn", { bg = c.gray_very_dark })
  h(0, "GitSignsDeleteLn", { bg = c.gray_very_dark })
  h(0, "GitSignsCurrentLineBlame", { fg = c.gray_dark })

  -- Telescope
  h(0, "TelescopeNormal", { bg = c.bg, fg = c.fg })
  h(0, "TelescopeBorder", { fg = c.gray_dark, bg = c.bg })
  h(0, "TelescopePromptNormal", { bg = c.black, fg = c.fg })
  h(0, "TelescopePromptBorder", { fg = c.gray_dark, bg = c.black })
  h(0, "TelescopePromptTitle", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "TelescopePreviewTitle", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "TelescopeResultsTitle", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "TelescopeSelection", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "TelescopeSelectionCaret", { fg = c.white, bold = true })
  h(0, "TelescopeMultiSelection", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "TelescopeMatching", { fg = c.white, bold = true })

  -- WhichKey
  h(0, "WhichKey", { fg = c.white, bold = true })
  h(0, "WhichKeyGroup", { fg = c.gray_lighter })
  h(0, "WhichKeyDesc", { fg = c.fg })
  h(0, "WhichKeySeperator", { fg = c.gray_dark })
  h(0, "WhichKeySeparator", { fg = c.gray_dark })
  h(0, "WhichKeyValue", { fg = c.gray })
  h(0, "WhichKeyBorder", { fg = c.gray_dark })
  h(0, "WhichKeyFloat", { bg = c.black })

  -- NeoTree / NvimTree
  h(0, "NeoTreeNormal", { bg = c.bg, fg = c.fg })
  h(0, "NeoTreeNormalNC", { bg = c.bg, fg = c.gray })
  h(0, "NeoTreeRootName", { fg = c.white, bold = true })
  h(0, "NeoTreeFileName", { fg = c.fg })
  h(0, "NeoTreeFileNameOpened", { fg = c.white, bold = true })
  h(0, "NeoTreeDirectoryName", { fg = c.gray_lighter })
  h(0, "NeoTreeDirectoryIcon", { fg = c.gray_light })
  h(0, "NeoTreeIndentMarker", { fg = c.gray_dark })
  h(0, "NeoTreeGitAdded", { fg = c.gray_lighter })
  h(0, "NeoTreeGitModified", { fg = c.gray_light })
  h(0, "NeoTreeGitDeleted", { fg = c.gray })
  h(0, "NeoTreeGitConflict", { fg = c.white, bold = true })
  h(0, "NeoTreeGitUntracked", { fg = c.gray_light })
  h(0, "NeoTreeGitIgnored", { fg = c.gray_dark })

  -- Mason
  h(0, "MasonNormal", { bg = c.black, fg = c.fg })
  h(0, "MasonHeader", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "MasonHighlight", { fg = c.white, bold = true })
  h(0, "MasonHighlightBlock", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "MasonHighlightBlockBold", { bg = c.gray_dark, fg = c.white, bold = true })

  -- Cmp (autocomplete)
  h(0, "CmpItemAbbr", { fg = c.fg })
  h(0, "CmpItemAbbrDeprecated", { fg = c.gray, strikethrough = true })
  h(0, "CmpItemAbbrMatch", { fg = c.white, bold = true })
  h(0, "CmpItemAbbrMatchFuzzy", { fg = c.white, bold = true })
  h(0, "CmpItemKind", { fg = c.gray_light })
  h(0, "CmpItemMenu", { fg = c.gray })
  h(0, "CmpItemKindText", { fg = c.fg })
  h(0, "CmpItemKindMethod", { fg = c.white })
  h(0, "CmpItemKindFunction", { fg = c.white })
  h(0, "CmpItemKindConstructor", { fg = c.gray_lighter })
  h(0, "CmpItemKindField", { fg = c.fg })
  h(0, "CmpItemKindVariable", { fg = c.fg })
  h(0, "CmpItemKindClass", { fg = c.gray_lighter })
  h(0, "CmpItemKindInterface", { fg = c.gray_lighter })
  h(0, "CmpItemKindModule", { fg = c.gray_lighter })
  h(0, "CmpItemKindProperty", { fg = c.fg })
  h(0, "CmpItemKindUnit", { fg = c.gray_light })
  h(0, "CmpItemKindValue", { fg = c.gray_light })
  h(0, "CmpItemKindEnum", { fg = c.gray_lighter })
  h(0, "CmpItemKindKeyword", { fg = c.gray_lighter })
  h(0, "CmpItemKindSnippet", { fg = c.gray })
  h(0, "CmpItemKindColor", { fg = c.gray_light })
  h(0, "CmpItemKindFile", { fg = c.fg })
  h(0, "CmpItemKindReference", { fg = c.fg })
  h(0, "CmpItemKindFolder", { fg = c.gray_lighter })
  h(0, "CmpItemKindEnumMember", { fg = c.gray_light })
  h(0, "CmpItemKindConstant", { fg = c.gray_lighter })
  h(0, "CmpItemKindStruct", { fg = c.gray_lighter })
  h(0, "CmpItemKindEvent", { fg = c.gray_light })
  h(0, "CmpItemKindOperator", { fg = c.gray_mid })
  h(0, "CmpItemKindTypeParameter", { fg = c.gray_lighter })

  -- Notify
  h(0, "NotifyBackground", { bg = c.black })
  h(0, "NotifyERRORBorder", { fg = c.gray_dark })
  h(0, "NotifyWARNBorder", { fg = c.gray_dark })
  h(0, "NotifyINFOBorder", { fg = c.gray_dark })
  h(0, "NotifyDEBUGBorder", { fg = c.gray_dark })
  h(0, "NotifyTRACEBorder", { fg = c.gray_dark })
  h(0, "NotifyERRORIcon", { fg = c.gray_lighter })
  h(0, "NotifyWARNIcon", { fg = c.gray_light })
  h(0, "NotifyINFOIcon", { fg = c.gray })
  h(0, "NotifyDEBUGIcon", { fg = c.gray_dark })
  h(0, "NotifyTRACEIcon", { fg = c.gray_dark })
  h(0, "NotifyERRORTitle", { fg = c.gray_lighter, bold = true })
  h(0, "NotifyWARNTitle", { fg = c.gray_light, bold = true })
  h(0, "NotifyINFOTitle", { fg = c.gray, bold = true })
  h(0, "NotifyDEBUGTitle", { fg = c.gray_dark, bold = true })
  h(0, "NotifyTRACETitle", { fg = c.gray_dark, bold = true })
  h(0, "NotifyERRORBody", { fg = c.fg })
  h(0, "NotifyWARNBody", { fg = c.fg })
  h(0, "NotifyINFOBody", { fg = c.fg })
  h(0, "NotifyDEBUGBody", { fg = c.fg })
  h(0, "NotifyTRACEBody", { fg = c.fg })

  -- Lazy (plugin manager)
  h(0, "LazyNormal", { bg = c.black, fg = c.fg })
  h(0, "LazyButton", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "LazyButtonActive", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "LazyComment", { fg = c.gray, italic = true })
  h(0, "LazyCommit", { fg = c.gray_light })
  h(0, "LazyCommitIssue", { fg = c.gray })
  h(0, "LazyCommitType", { fg = c.gray_lighter })
  h(0, "LazyDir", { fg = c.gray_lighter })
  h(0, "LazyH1", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "LazyH2", { fg = c.gray_lighter, bold = true })
  h(0, "LazyProgressDone", { fg = c.white })
  h(0, "LazyProgressTodo", { fg = c.gray_dark })
  h(0, "LazyProp", { fg = c.gray })
  h(0, "LazyReasonCmd", { fg = c.gray_light })
  h(0, "LazyReasonEvent", { fg = c.gray_light })
  h(0, "LazyReasonFt", { fg = c.gray_light })
  h(0, "LazyReasonImport", { fg = c.gray_light })
  h(0, "LazyReasonKeys", { fg = c.gray_light })
  h(0, "LazyReasonPlugin", { fg = c.gray_light })
  h(0, "LazyReasonRuntime", { fg = c.gray_light })
  h(0, "LazyReasonSource", { fg = c.gray_light })
  h(0, "LazyReasonStart", { fg = c.gray_light })
  h(0, "LazySpecial", { fg = c.white, bold = true })
  h(0, "LazyTaskError", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "LazyTaskOutput", { fg = c.fg })
  h(0, "LazyUrl", { fg = c.gray_lighter, underline = true })
  h(0, "LazyValue", { fg = c.gray_lighter })

  -- Noice
  h(0, "NoiceCmdline", { bg = c.black, fg = c.fg })
  h(0, "NoiceCmdlineIcon", { fg = c.gray_light })
  h(0, "NoiceCmdlineIconSearch", { fg = c.white, bold = true })
  h(0, "NoiceCmdlinePopup", { bg = c.black, fg = c.fg })
  h(0, "NoiceCmdlinePopupBorder", { fg = c.gray_dark })
  h(0, "NoiceCmdlinePopupBorderSearch", { fg = c.gray_dark })
  h(0, "NoiceConfirm", { bg = c.black, fg = c.fg })
  h(0, "NoiceConfirmBorder", { fg = c.gray_dark })
  h(0, "NoiceMini", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "NoicePopup", { bg = c.black, fg = c.fg })
  h(0, "NoicePopupBorder", { fg = c.gray_dark })
  h(0, "NoicePopupmenu", { bg = c.black, fg = c.fg })
  h(0, "NoicePopupmenuBorder", { fg = c.gray_dark })
  h(0, "NoicePopupmenuMatch", { fg = c.white, bold = true })
  h(0, "NoicePopupmenuSelected", { bg = c.gray_dark, fg = c.white })
  h(0, "NoiceFormatProgressDone", { bg = c.gray_dark, fg = c.white })
  h(0, "NoiceFormatProgressTodo", { bg = c.gray_very_dark, fg = c.gray })
  h(0, "NoiceFormatSearchVirtualText", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "NoiceFormatTitle", { fg = c.white, bold = true })
  h(0, "NoiceFormatEvent", { fg = c.gray_light })
  h(0, "NoiceFormatKind", { fg = c.gray_lighter })
  h(0, "NoiceCursor", { bg = c.cursor, fg = c.bg })

  -- Flash (search plugin)
  h(0, "FlashLabel", { bg = c.white, fg = c.black, bold = true })
  h(0, "FlashMatch", { bg = c.gray_dark, fg = c.white })
  h(0, "FlashCurrent", { bg = c.gray_lighter, fg = c.black, bold = true })
  h(0, "FlashPrompt", { bg = c.black, fg = c.fg })
  h(0, "FlashPromptIcon", { fg = c.gray_light })
  h(0, "FlashCursor", { bg = c.cursor, fg = c.bg })

  -- Bufferline / Tabline
  h(0, "BufferLineFill", { bg = c.bg })
  h(0, "BufferLineBackground", { bg = c.black, fg = c.gray })
  h(0, "BufferLineBufferVisible", { bg = c.black, fg = c.gray })
  h(0, "BufferLineBufferSelected", { bg = c.bg, fg = c.white, bold = true, italic = false })
  h(0, "BufferLineTab", { bg = c.black, fg = c.fg })
  h(0, "BufferLineTabSelected", { bg = c.bg, fg = c.white, bold = true })
  h(0, "BufferLineTabClose", { fg = c.gray })
  h(0, "BufferLineIndicatorSelected", { fg = c.white })
  h(0, "BufferLineSeparator", { fg = c.black, bg = c.black })
  h(0, "BufferLineSeparatorVisible", { fg = c.black, bg = c.black })
  h(0, "BufferLineSeparatorSelected", { fg = c.black, bg = c.bg })
  h(0, "BufferLineCloseButton", { fg = c.gray })
  h(0, "BufferLineCloseButtonVisible", { fg = c.gray })
  h(0, "BufferLineCloseButtonSelected", { fg = c.gray_lighter })
  h(0, "BufferLineModified", { fg = c.gray_lighter })
  h(0, "BufferLineModifiedVisible", { fg = c.gray_lighter })
  h(0, "BufferLineModifiedSelected", { fg = c.white, bold = true })
  h(0, "BufferLineDuplicate", { fg = c.gray_dark })
  h(0, "BufferLineDuplicateVisible", { fg = c.gray_dark })
  h(0, "BufferLineDuplicateSelected", { fg = c.gray })
  h(0, "BufferLinePick", { fg = c.white, bold = true })
  h(0, "BufferLinePickSelected", { fg = c.white, bold = true })
  h(0, "BufferLinePickVisible", { fg = c.white, bold = true })
  h(0, "BufferLineError", { fg = c.gray_lighter, bg = c.gray_very_dark })
  h(0, "BufferLineErrorVisible", { fg = c.gray_lighter, bg = c.black })
  h(0, "BufferLineErrorSelected", { fg = c.white, bg = c.bg, bold = true })
  h(0, "BufferLineErrorDiagnostic", { fg = c.gray })
  h(0, "BufferLineErrorDiagnosticVisible", { fg = c.gray })
  h(0, "BufferLineErrorDiagnosticSelected", { fg = c.gray_lighter, bold = true })
  h(0, "BufferLineWarning", { fg = c.gray_light, bg = c.gray_very_dark })
  h(0, "BufferLineWarningVisible", { fg = c.gray_light, bg = c.black })
  h(0, "BufferLineWarningSelected", { fg = c.white, bg = c.bg, bold = true })
  h(0, "BufferLineWarningDiagnostic", { fg = c.gray })
  h(0, "BufferLineWarningDiagnosticVisible", { fg = c.gray })
  h(0, "BufferLineWarningDiagnosticSelected", { fg = c.gray_light, bold = true })
  h(0, "BufferLineInfo", { fg = c.gray, bg = c.gray_very_dark })
  h(0, "BufferLineInfoVisible", { fg = c.gray, bg = c.black })
  h(0, "BufferLineInfoSelected", { fg = c.white, bg = c.bg, bold = true })
  h(0, "BufferLineInfoDiagnostic", { fg = c.gray_dark })
  h(0, "BufferLineInfoDiagnosticVisible", { fg = c.gray_dark })
  h(0, "BufferLineInfoDiagnosticSelected", { fg = c.gray, bold = true })
  h(0, "BufferLineHint", { fg = c.gray_dark, bg = c.gray_very_dark })
  h(0, "BufferLineHintVisible", { fg = c.gray_dark, bg = c.black })
  h(0, "BufferLineHintSelected", { fg = c.white, bg = c.bg, bold = true })
  h(0, "BufferLineHintDiagnostic", { fg = c.gray_dark })
  h(0, "BufferLineHintDiagnosticVisible", { fg = c.gray_dark })
  h(0, "BufferLineHintDiagnosticSelected", { fg = c.gray, bold = true })
  h(0, "BufferLineDiagnostic", { fg = c.gray_dark })
  h(0, "BufferLineDiagnosticVisible", { fg = c.gray_dark })
  h(0, "BufferLineDiagnosticSelected", { fg = c.gray, bold = true })
  h(0, "BufferLineNumbers", { fg = c.gray_dark })
  h(0, "BufferLineNumbersSelected", { fg = c.gray, bold = true })
  h(0, "BufferLineOffsetSeparator", { fg = c.black, bg = c.black })
  h(0, "BufferLineGroupLabel", { bg = c.gray_dark, fg = c.black })
  h(0, "BufferLineGroupSeparator", { fg = c.gray_dark })

  -- Navic (winbar)
  h(0, "NavicText", { fg = c.fg })
  h(0, "NavicSeparator", { fg = c.gray_dark })
  h(0, "NavicIconsFile", { fg = c.fg })
  h(0, "NavicIconsModule", { fg = c.gray_lighter })
  h(0, "NavicIconsNamespace", { fg = c.gray_lighter })
  h(0, "NavicIconsPackage", { fg = c.gray_lighter })
  h(0, "NavicIconsClass", { fg = c.gray_lighter })
  h(0, "NavicIconsMethod", { fg = c.white })
  h(0, "NavicIconsProperty", { fg = c.fg })
  h(0, "NavicIconsField", { fg = c.fg })
  h(0, "NavicIconsConstructor", { fg = c.gray_lighter })
  h(0, "NavicIconsEnum", { fg = c.gray_lighter })
  h(0, "NavicIconsInterface", { fg = c.gray_lighter })
  h(0, "NavicIconsFunction", { fg = c.white })
  h(0, "NavicIconsVariable", { fg = c.fg })
  h(0, "NavicIconsConstant", { fg = c.gray_lighter })
  h(0, "NavicIconsString", { fg = c.gray_lighter })
  h(0, "NavicIconsNumber", { fg = c.gray_light })
  h(0, "NavicIconsBoolean", { fg = c.gray_lighter })
  h(0, "NavicIconsArray", { fg = c.gray_lighter })
  h(0, "NavicIconsObject", { fg = c.gray_lighter })
  h(0, "NavicIconsKey", { fg = c.gray_lighter })
  h(0, "NavicIconsNull", { fg = c.gray_light })
  h(0, "NavicIconsEnumMember", { fg = c.gray_light })
  h(0, "NavicIconsStruct", { fg = c.gray_lighter })
  h(0, "NavicIconsEvent", { fg = c.gray_light })
  h(0, "NavicIconsOperator", { fg = c.gray_mid })
  h(0, "NavicIconsTypeParameter", { fg = c.gray_lighter })

  -- Illuminate
  h(0, "IlluminatedWordText", { bg = c.gray_dark })
  h(0, "IlluminatedWordRead", { bg = c.gray_dark })
  h(0, "IlluminatedWordWrite", { bg = c.gray_dark, underline = true })

  -- Indent Blankline
  h(0, "IblIndent", { fg = c.gray_very_dark })
  h(0, "IblScope", { fg = c.gray_dark })
  h(0, "IblWhitespace", { fg = c.gray_very_dark })

  -- Scrollbar
  h(0, "ScrollbarHandle", { bg = c.gray_dark })
  h(0, "ScrollbarSearch", { fg = c.white, bg = c.gray_dark })
  h(0, "ScrollbarError", { fg = c.gray_lighter, bg = c.gray_dark })
  h(0, "ScrollbarWarn", { fg = c.gray_light, bg = c.gray_dark })
  h(0, "ScrollbarInfo", { fg = c.gray, bg = c.gray_dark })
  h(0, "ScrollbarHint", { fg = c.gray_dark, bg = c.gray_very_dark })
  h(0, "ScrollbarMisc", { fg = c.gray, bg = c.gray_dark })
  h(0, "ScrollbarCursor", { bg = c.gray_dark })
  h(0, "ScrollbarCursorHandle", { bg = c.gray_dark })

  -- Hop / Leap / Lightspeed
  h(0, "HopNextKey", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "HopNextKey1", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "HopNextKey2", { fg = c.gray_light, bg = c.gray_very_dark })
  h(0, "HopUnmatched", { fg = c.gray_dark })
  h(0, "HopPreview", { fg = c.black, bg = c.white, bold = true })

  -- Sneak
  h(0, "Sneak", { fg = c.black, bg = c.white, bold = true })
  h(0, "SneakScope", { bg = c.gray_dark })
  h(0, "SneakLabel", { fg = c.black, bg = c.white, bold = true })
  h(0, "SneakLabelMask", { fg = c.white })

  -- Rainbow delimiters
  h(0, "RainbowDelimiterRed", { fg = c.gray_lighter })
  h(0, "RainbowDelimiterYellow", { fg = c.gray_light })
  h(0, "RainbowDelimiterBlue", { fg = c.fg })
  h(0, "RainbowDelimiterOrange", { fg = c.gray_mid })
  h(0, "RainbowDelimiterGreen", { fg = c.gray })
  h(0, "RainbowDelimiterViolet", { fg = c.gray_dark })
  h(0, "RainbowDelimiterCyan", { fg = c.white })

  -- Neotest
  h(0, "NeotestPassed", { fg = c.gray_lighter })
  h(0, "NeotestFailed", { fg = c.gray })
  h(0, "NeotestRunning", { fg = c.gray_light })
  h(0, "NeotestSkipped", { fg = c.gray_dark })
  h(0, "NeotestTest", { fg = c.fg })
  h(0, "NeotestNamespace", { fg = c.gray_lighter })
  h(0, "NeotestMarked", { fg = c.white, bold = true })
  h(0, "NeotestFocused", { fg = c.white, bold = true })
  h(0, "NeotestFile", { fg = c.gray_light })
  h(0, "NeotestDir", { fg = c.gray_lighter })
  h(0, "NeotestBroadcast", { fg = c.gray_light })
  h(0, "NeotestRunning", { fg = c.gray_light })
  h(0, "NeotestAdapterName", { fg = c.gray, bold = true })

  -- Overseer
  h(0, "OverseerPENDING", { fg = c.gray })
  h(0, "OverseerRUNNING", { fg = c.gray_light })
  h(0, "OverseerCANCELED", { fg = c.gray_dark })
  h(0, "OverseerSUCCESS", { fg = c.gray_lighter })
  h(0, "OverseerFAILURE", { fg = c.gray })
  h(0, "OverseerTaskBorder", { fg = c.gray_dark })
  h(0, "OverseerOutput", { fg = c.fg })
  h(0, "OverseerComponent", { fg = c.gray })
  h(0, "OverseerField", { fg = c.gray_light })

  -- Satellite (scrollbar)
  h(0, "SatelliteBar", { bg = c.gray_dark })
  h(0, "SatelliteCursor", { bg = c.gray_very_dark })

  -- Dap (debugging)
  h(0, "DapBreakpoint", { fg = c.gray })
  h(0, "DapBreakpointCondition", { fg = c.gray_light })
  h(0, "DapBreakpointRejected", { fg = c.gray_dark })
  h(0, "DapLogPoint", { fg = c.gray_lighter })
  h(0, "DapStopped", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "DapUIPlayPause", { fg = c.gray_lighter })
  h(0, "DapUIRestart", { fg = c.gray_lighter })
  h(0, "DapUIStop", { fg = c.gray })
  h(0, "DapUIStepOver", { fg = c.gray_light })
  h(0, "DapUIStepInto", { fg = c.gray_light })
  h(0, "DapUIStepOut", { fg = c.gray_light })
  h(0, "DapUIStepBack", { fg = c.gray_light })
  h(0, "DapUIWatchesEmpty", { fg = c.gray })
  h(0, "DapUIWatchesValue", { fg = c.gray_lighter })
  h(0, "DapUIWatchesError", { fg = c.gray_dark })
  h(0, "DapUIType", { fg = c.gray })
  h(0, "DapUIScope", { fg = c.gray_lighter })
  h(0, "DapUIVariable", { fg = c.fg })
  h(0, "DapUIValue", { fg = c.gray_lighter })
  h(0, "DapUIFrameName", { fg = c.fg })
  h(0, "DapUISource", { fg = c.gray_light })
  h(0, "DapUILineNumber", { fg = c.gray_dark })
  h(0, "DapUIFloatBorder", { fg = c.gray_dark })
  h(0, "DapUIThread", { fg = c.gray_lighter })
  h(0, "DapUIStoppedThread", { fg = c.white, bold = true })
  h(0, "DapUIUnavailable", { fg = c.gray_dark })
  h(0, "DapUIWinSelect", { fg = c.white, bold = true })
  h(0, "DapUIBreakpointsPath", { fg = c.gray_lighter })
  h(0, "DapUIBreakpointsInfo", { fg = c.gray })
  h(0, "DapUIBreakpointsCurrentLine", { fg = c.white, bold = true })
  h(0, "DapUIBreakpointsLine", { fg = c.fg })
  h(0, "DapUIBreakpointsDisabledLine", { fg = c.gray_dark })

  -- Barbar (bufferline alternative)
  h(0, "BufferCurrent", { bg = c.bg, fg = c.white, bold = true })
  h(0, "BufferCurrentIndex", { bg = c.bg, fg = c.gray })
  h(0, "BufferCurrentMod", { bg = c.bg, fg = c.gray_lighter, bold = true })
  h(0, "BufferCurrentSign", { bg = c.bg, fg = c.white })
  h(0, "BufferCurrentTarget", { bg = c.bg, fg = c.white, bold = true })
  h(0, "BufferVisible", { bg = c.black, fg = c.gray })
  h(0, "BufferVisibleIndex", { bg = c.black, fg = c.gray_dark })
  h(0, "BufferVisibleMod", { bg = c.black, fg = c.gray_light })
  h(0, "BufferVisibleSign", { bg = c.black, fg = c.gray })
  h(0, "BufferVisibleTarget", { bg = c.black, fg = c.white, bold = true })
  h(0, "BufferInactive", { bg = c.black, fg = c.gray })
  h(0, "BufferInactiveIndex", { bg = c.black, fg = c.gray_dark })
  h(0, "BufferInactiveMod", { bg = c.black, fg = c.gray_light })
  h(0, "BufferInactiveSign", { bg = c.black, fg = c.gray_dark })
  h(0, "BufferInactiveTarget", { bg = c.black, fg = c.white, bold = true })
  h(0, "BufferTabpages", { bg = c.black, fg = c.gray, bold = true })
  h(0, "BufferTabpage", { bg = c.black, fg = c.gray_dark })

  -- Trouble
  h(0, "TroubleText", { fg = c.fg })
  h(0, "TroubleCount", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "TroubleNormal", { bg = c.black, fg = c.fg })
  h(0, "TroubleSignError", { fg = c.gray_lighter })
  h(0, "TroubleSignWarning", { fg = c.gray_light })
  h(0, "TroubleSignInformation", { fg = c.gray })
  h(0, "TroubleSignHint", { fg = c.gray_dark })
  h(0, "TroubleSignOther", { fg = c.gray })
  h(0, "TroubleFoldIcon", { fg = c.gray })
  h(0, "TroubleIndent", { fg = c.gray_very_dark })
  h(0, "TroubleLocation", { fg = c.gray_dark })
  h(0, "TroubleCode", { fg = c.gray_light })
  h(0, "TroubleSource", { fg = c.gray })
  h(0, "TroubleFile", { fg = c.gray_lighter })
  h(0, "TroubleError", { fg = c.gray_lighter })
  h(0, "TroubleWarning", { fg = c.gray_light })
  h(0, "TroubleInformation", { fg = c.gray })
  h(0, "TroubleHint", { fg = c.gray_dark })
  h(0, "TroublePreview", { bg = c.gray_very_dark })

  -- Aerial
  h(0, "AerialNormal", { bg = c.bg, fg = c.fg })
  h(0, "AerialGuide", { fg = c.gray_dark })
  h(0, "AerialLine", { bg = c.gray_very_dark })
  h(0, "AerialLineNC", { bg = c.black })
  h(0, "AerialIcon", { fg = c.gray_light })

  -- SymbolsOutline
  h(0, "SymbolsOutlineConnector", { fg = c.gray_dark })
  h(0, "SymbolsOutlineIndentMarker", { fg = c.gray_very_dark })

  -- nvim-ufo (folding)
  h(0, "UfoFoldedBg", { bg = c.gray_very_dark })
  h(0, "UfoFoldedFg", { fg = c.gray_light })
  h(0, "UfoPreviewSbar", { bg = c.gray_very_dark })
  h(0, "UfoPreviewThumb", { bg = c.gray })
  h(0, "UfoPreviewCursorLine", { bg = c.gray_dark })
  h(0, "UfoPreviewBufSeparator", { fg = c.gray_dark })
  h(0, "UfoFoldedEllipsis", { fg = c.gray })
  h(0, "UfoCursorFoldedLine", { bg = c.gray_very_dark })
  h(0, "UfoCursorLine", { bg = c.gray_very_dark })

  -- Glance (LSP hover UI)
  h(0, "GlanceBorderTop", { fg = c.gray_dark })
  h(0, "GlanceWinBarFilename", { fg = c.gray, bg = c.black })
  h(0, "GlanceWinBarFilepath", { fg = c.gray_dark, bg = c.black })
  h(0, "GlanceListNormal", { bg = c.black, fg = c.fg })
  h(0, "GlanceListFilename", { fg = c.gray_lighter })
  h(0, "GlanceListFilepath", { fg = c.gray })
  h(0, "GlanceListCount", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "GlanceListMatch", { fg = c.white, bold = true })
  h(0, "GlanceListCursorLine", { bg = c.gray_very_dark })
  h(0, "GlancePreviewNormal", { bg = c.bg, fg = c.fg })
  h(0, "GlancePreviewMatch", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "GlancePreviewCursorLine", { bg = c.gray_very_dark })
  h(0, "GlancePreviewCursorLineNr", { bg = c.gray_very_dark, fg = c.gray })
  h(0, "GlancePreviewSignColumn", { bg = c.bg })
  h(0, "GlancePreviewEndOfBuffer", { fg = c.gray_very_dark })
  h(0, "GlancePreviewLineNr", { fg = c.gray_dark })
  h(0, "GlancePreviewBorderBottom", { fg = c.gray_dark })

  -- Dropbar
  h(0, "DropBarIcon", { fg = c.gray_light })
  h(0, "DropBarIconUISeparator", { fg = c.gray_dark })
  h(0, "DropBarIconUIPickPivot", { fg = c.white, bold = true })
  h(0, "DropBarIconCurrentContext", { fg = c.white, bold = true })
  h(0, "DropBarIconKindArray", { fg = c.gray_lighter })
  h(0, "DropBarIconKindBoolean", { fg = c.gray_lighter })
  h(0, "DropBarIconKindClass", { fg = c.gray_lighter })
  h(0, "DropBarIconKindConstant", { fg = c.gray_lighter })
  h(0, "DropBarIconKindConstructor", { fg = c.gray_lighter })
  h(0, "DropBarIconKindEnum", { fg = c.gray_lighter })
  h(0, "DropBarIconKindEnumMember", { fg = c.gray_light })
  h(0, "DropBarIconKindEvent", { fg = c.gray_light })
  h(0, "DropBarIconKindField", { fg = c.fg })
  h(0, "DropBarIconKindFile", { fg = c.fg })
  h(0, "DropBarIconKindFunction", { fg = c.white })
  h(0, "DropBarIconKindInterface", { fg = c.gray_lighter })
  h(0, "DropBarIconKindKey", { fg = c.gray_lighter })
  h(0, "DropBarIconKindKeyword", { fg = c.gray_lighter })
  h(0, "DropBarIconKindMethod", { fg = c.white })
  h(0, "DropBarIconKindModule", { fg = c.gray_lighter })
  h(0, "DropBarIconKindNamespace", { fg = c.gray_lighter })
  h(0, "DropBarIconKindNull", { fg = c.gray_light })
  h(0, "DropBarIconKindNumber", { fg = c.gray_light })
  h(0, "DropBarIconKindObject", { fg = c.gray_lighter })
  h(0, "DropBarIconKindOperator", { fg = c.gray_mid })
  h(0, "DropBarIconKindPackage", { fg = c.gray_lighter })
  h(0, "DropBarIconKindProperty", { fg = c.fg })
  h(0, "DropBarIconKindString", { fg = c.gray_lighter })
  h(0, "DropBarIconKindStruct", { fg = c.gray_lighter })
  h(0, "DropBarIconKindTypeParameter", { fg = c.gray_lighter })
  h(0, "DropBarIconKindVariable", { fg = c.fg })
  h(0, "DropBarKindArray", { fg = c.gray_lighter })
  h(0, "DropBarKindBoolean", { fg = c.gray_lighter })
  h(0, "DropBarKindClass", { fg = c.gray_lighter })
  h(0, "DropBarKindConstant", { fg = c.gray_lighter })
  h(0, "DropBarKindConstructor", { fg = c.gray_lighter })
  h(0, "DropBarKindEnum", { fg = c.gray_lighter })
  h(0, "DropBarKindEnumMember", { fg = c.gray_light })
  h(0, "DropBarKindEvent", { fg = c.gray_light })
  h(0, "DropBarKindField", { fg = c.fg })
  h(0, "DropBarKindFile", { fg = c.fg })
  h(0, "DropBarKindFunction", { fg = c.white })
  h(0, "DropBarKindInterface", { fg = c.gray_lighter })
  h(0, "DropBarKindKey", { fg = c.gray_lighter })
  h(0, "DropBarKindKeyword", { fg = c.gray_lighter })
  h(0, "DropBarKindMethod", { fg = c.white })
  h(0, "DropBarKindModule", { fg = c.gray_lighter })
  h(0, "DropBarKindNamespace", { fg = c.gray_lighter })
  h(0, "DropBarKindNull", { fg = c.gray_light })
  h(0, "DropBarKindNumber", { fg = c.gray_light })
  h(0, "DropBarKindObject", { fg = c.gray_lighter })
  h(0, "DropBarKindOperator", { fg = c.gray_mid })
  h(0, "DropBarKindPackage", { fg = c.gray_lighter })
  h(0, "DropBarKindProperty", { fg = c.fg })
  h(0, "DropBarKindString", { fg = c.gray_lighter })
  h(0, "DropBarKindStruct", { fg = c.gray_lighter })
  h(0, "DropBarKindTypeParameter", { fg = c.gray_lighter })
  h(0, "DropBarKindVariable", { fg = c.fg })
  h(0, "DropBarMenuCurrentContext", { bg = c.gray_very_dark })
  h(0, "DropBarMenuFloatBorder", { fg = c.gray_dark })
  h(0, "DropBarMenuHoverEntry", { bg = c.gray_dark })
  h(0, "DropBarMenuHoverIcon", { bg = c.gray_dark })
  h(0, "DropBarMenuHoverSymbol", { bg = c.gray_dark })
  h(0, "DropBarMenuNormalFloat", { bg = c.black, fg = c.fg })
  h(0, "DropBarPreview", { bg = c.gray_very_dark })
  h(0, "DropBarMenuSbar", { bg = c.gray_very_dark })
  h(0, "DropBarMenuThumb", { bg = c.gray })

  -- RenderMarkdown
  h(0, "RenderMarkdownBullet", { fg = c.gray })
  h(0, "RenderMarkdownCheckbox", { fg = c.gray })
  h(0, "RenderMarkdownChecked", { fg = c.gray_lighter })
  h(0, "RenderMarkdownQuote", { fg = c.gray })
  h(0, "RenderMarkdownDash", { fg = c.gray_dark })
  h(0, "RenderMarkdownTableHead", { fg = c.gray_lighter, bold = true })
  h(0, "RenderMarkdownTableRow", { fg = c.fg })
  h(0, "RenderMarkdownTableFill", { fg = c.gray_dark })
  h(0, "RenderMarkdownCode", { bg = c.gray_very_dark })
  h(0, "RenderMarkdownCodeInline", { bg = c.gray_very_dark })
  h(0, "RenderMarkdownH1", { fg = c.white, bold = true })
  h(0, "RenderMarkdownH2", { fg = c.gray_lighter, bold = true })
  h(0, "RenderMarkdownH3", { fg = c.gray_lighter, bold = true })
  h(0, "RenderMarkdownH4", { fg = c.fg, bold = true })
  h(0, "RenderMarkdownH5", { fg = c.fg, bold = true })
  h(0, "RenderMarkdownH6", { fg = c.gray, bold = true })
  h(0, "RenderMarkdownH1Bg", { bg = c.gray_very_dark })
  h(0, "RenderMarkdownH2Bg", { bg = c.gray_very_dark })
  h(0, "RenderMarkdownH3Bg", { bg = c.gray_very_dark })
  h(0, "RenderMarkdownH4Bg", { bg = c.gray_very_dark })
  h(0, "RenderMarkdownH5Bg", { bg = c.gray_very_dark })
  h(0, "RenderMarkdownH6Bg", { bg = c.gray_very_dark })

  -- Headlines
  h(0, "Headline", { bg = c.gray_very_dark, bold = true })
  h(0, "CodeBlock", { bg = c.gray_very_dark })
  h(0, "Dash", { fg = c.gray_dark, bold = true })

  -- Mini.icons
  h(0, "MiniIconsAzure", { fg = c.gray_light })
  h(0, "MiniIconsBlue", { fg = c.fg })
  h(0, "MiniIconsCyan", { fg = c.gray_lighter })
  h(0, "MiniIconsGreen", { fg = c.gray })
  h(0, "MiniIconsGrey", { fg = c.gray })
  h(0, "MiniIconsOrange", { fg = c.gray_mid })
  h(0, "MiniIconsPurple", { fg = c.gray_light })
  h(0, "MiniIconsRed", { fg = c.gray_dark })
  h(0, "MiniIconsYellow", { fg = c.gray_lighter })

  -- Snacks (folke's utility library)
  h(0, "SnacksNormal", { bg = c.black, fg = c.fg })
  h(0, "SnacksNormalNC", { bg = c.black, fg = c.gray })
  h(0, "SnacksNotifierInfo", { fg = c.gray })
  h(0, "SnacksNotifierDebug", { fg = c.gray_dark })
  h(0, "SnacksNotifierTrace", { fg = c.gray_dark })
  h(0, "SnacksNotifierWarn", { fg = c.gray_light })
  h(0, "SnacksNotifierError", { fg = c.gray_lighter })
  h(0, "SnacksNotifierTitleInfo", { fg = c.gray, bold = true })
  h(0, "SnacksNotifierTitleDebug", { fg = c.gray_dark, bold = true })
  h(0, "SnacksNotifierTitleTrace", { fg = c.gray_dark, bold = true })
  h(0, "SnacksNotifierTitleWarn", { fg = c.gray_light, bold = true })
  h(0, "SnacksNotifierTitleError", { fg = c.gray_lighter, bold = true })
  h(0, "SnacksNotifierBorderInfo", { fg = c.gray_dark })
  h(0, "SnacksNotifierBorderDebug", { fg = c.gray_dark })
  h(0, "SnacksNotifierBorderTrace", { fg = c.gray_dark })
  h(0, "SnacksNotifierBorderWarn", { fg = c.gray_dark })
  h(0, "SnacksNotifierBorderError", { fg = c.gray_dark })
  h(0, "SnacksNotifierIconInfo", { fg = c.gray })
  h(0, "SnacksNotifierIconDebug", { fg = c.gray_dark })
  h(0, "SnacksNotifierIconTrace", { fg = c.gray_dark })
  h(0, "SnacksNotifierIconWarn", { fg = c.gray_light })
  h(0, "SnacksNotifierIconError", { fg = c.gray_lighter })
  h(0, "SnacksIndent", { fg = c.gray_very_dark })
  h(0, "SnacksIndentScope", { fg = c.gray_dark })
  h(0, "SnacksDashboardHeader", { fg = c.white, bold = true })
  h(0, "SnacksDashboardFooter", { fg = c.gray, italic = true })
  h(0, "SnacksDashboardDesc", { fg = c.fg })
  h(0, "SnacksDashboardIcon", { fg = c.gray_light })
  h(0, "SnacksDashboardKey", { fg = c.white, bold = true })
  h(0, "SnacksDashboardSpecial", { fg = c.gray_lighter })
  h(0, "SnacksDashboardDir", { fg = c.gray })
  h(0, "SnacksDashboardFile", { fg = c.fg })
  h(0, "SnacksPickerBorder", { fg = c.gray_dark })
  h(0, "SnacksPickerTitle", { fg = c.white, bold = true })
  h(0, "SnacksPickerPreviewTitle", { fg = c.white, bold = true })
  h(0, "SnacksPickerPrompt", { fg = c.gray_lighter, bold = true })
  h(0, "SnacksPickerMatch", { fg = c.white, bold = true })
  h(0, "SnacksPickerCursorLine", { bg = c.gray_dark })
  h(0, "SnacksPickerSelected", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "SnacksPickerToggle", { fg = c.gray })

  -- Yanky
  h(0, "YankyPut", { bg = c.gray_dark })
  h(0, "YankyYanked", { bg = c.gray_dark })

  -- Harpoon
  h(0, "HarpoonWindow", { bg = c.black, fg = c.fg })
  h(0, "HarpoonBorder", { fg = c.gray_dark })

  -- Outline (symbol outline)
  h(0, "OutlineFoldMarker", { fg = c.gray })
  h(0, "OutlineGuides", { fg = c.gray_dark })
  h(0, "OutlineIcon", { fg = c.gray_light })
  h(0, "OutlineIndentEmpty", { fg = c.gray_very_dark })
  h(0, "OutlineLevel1", { fg = c.white, bold = true })
  h(0, "OutlineLevel2", { fg = c.gray_lighter, bold = true })
  h(0, "OutlineLevel3", { fg = c.fg, bold = true })
  h(0, "OutlineLevel4", { fg = c.fg })
  h(0, "OutlineLevel5", { fg = c.gray })
  h(0, "OutlineLevel6", { fg = c.gray })

  -- FzfLua
  h(0, "FzfLuaNormal", { bg = c.black, fg = c.fg })
  h(0, "FzfLuaBorder", { fg = c.gray_dark, bg = c.black })
  h(0, "FzfLuaTitle", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "FzfLuaPreviewTitle", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "FzfLuaCursorLine", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "FzfLuaCursorLineNr", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "FzfLuaSearch", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "FzfLuaPrompt", { fg = c.gray_lighter, bold = true })
  h(0, "FzfLuaPointer", { fg = c.white, bold = true })
  h(0, "FzfLuaMarker", { fg = c.white, bold = true })
  h(0, "FzfLuaFzfNormal", { fg = c.fg })
  h(0, "FzfLuaFzfCursorLine", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "FzfLuaFzfMatch", { fg = c.white, bold = true })
  h(0, "FzfLuaFzfPrompt", { fg = c.gray_lighter })
  h(0, "FzfLuaFzfPointer", { fg = c.white })
  h(0, "FzfLuaFzfMarker", { fg = c.white })
  h(0, "FzfLuaFzfSpinner", { fg = c.gray_light })
  h(0, "FzfLuaFzfHeader", { fg = c.gray_lighter })
  h(0, "FzfLuaFzfInfo", { fg = c.gray })
  h(0, "FzfLuaFzfScrollbar", { fg = c.gray_dark })
  h(0, "FzfLuaFzfSeparator", { fg = c.gray_dark })
  h(0, "FzfLuaFzfGutter", { bg = c.black })
  h(0, "FzfLuaFzfQuery", { fg = c.fg })
  h(0, "FzfLuaFzfBuffer", { fg = c.fg })
  h(0, "FzfLuaFzfLines", { fg = c.fg })
  h(0, "FzfLuaFzfDevicons", { fg = c.fg })
  h(0, "FzfLuaFzfDirIcon", { fg = c.gray_lighter })
  h(0, "FzfLuaFzfDirPart", { fg = c.gray })
  h(0, "FzfLuaFzfFilePart", { fg = c.fg })
  h(0, "FzfLuaPathLineNr", { fg = c.gray_dark })
  h(0, "FzfLuaPathColNr", { fg = c.gray_dark })
  h(0, "FzfLuaBufName", { fg = c.gray_lighter })
  h(0, "FzfLuaBufNr", { fg = c.gray })
  h(0, "FzfLuaBufFlagCur", { fg = c.white })
  h(0, "FzfLuaBufFlagAlt", { fg = c.gray_light })
  h(0, "FzfLuaTabTitle", { fg = c.gray_lighter })
  h(0, "FzfLuaTabMarker", { fg = c.white })
  h(0, "FzfLuaHelpNormal", { fg = c.fg })
  h(0, "FzfLuaHelpBorder", { fg = c.gray_dark })
  h(0, "FzfLuaPreviewNormal", { bg = c.bg, fg = c.fg })
  h(0, "FzfLuaPreviewBorder", { fg = c.gray_dark, bg = c.bg })
  h(0, "FzfLuaPreviewCursorLine", { bg = c.gray_very_dark })
  h(0, "FzfLuaPreviewCursorLineNr", { bg = c.gray_very_dark, fg = c.gray })
  h(0, "FzfLuaPreviewMatch", { fg = c.white, bg = c.gray_dark, bold = true })
  h(0, "FzfLuaPreviewScrollbar", { bg = c.gray_very_dark })
  h(0, "FzfLuaPreviewScrollBorderEmpty", { fg = c.gray_very_dark })
  h(0, "FzfLuaPreviewScrollBorderFill", { fg = c.gray })
  h(0, "FzfLuaPreviewHeader", { fg = c.gray_lighter })
  h(0, "FzfLuaPreviewIncSearch", { fg = c.white, bg = c.gray_dark, bold = true })

  -- Treesitter Context
  h(0, "TreesitterContext", { bg = c.gray_very_dark })
  h(0, "TreesitterContextBottom", { sp = c.gray_dark, underline = true })
  h(0, "TreesitterContextLineNumber", { fg = c.gray_dark, bg = c.gray_very_dark })
  h(0, "TreesitterContextLineNumberBottom", { fg = c.gray, bg = c.gray_very_dark })

  -- Notify (legacy highlights for compatibility)
  h(0, "NotifyERRORBorder", { fg = c.gray_dark })
  h(0, "NotifyWARNBorder", { fg = c.gray_dark })
  h(0, "NotifyINFOBorder", { fg = c.gray_dark })
  h(0, "NotifyDEBUGBorder", { fg = c.gray_dark })
  h(0, "NotifyTRACEBorder", { fg = c.gray_dark })
  h(0, "NotifyERRORIcon", { fg = c.gray_lighter })
  h(0, "NotifyWARNIcon", { fg = c.gray_light })
  h(0, "NotifyINFOIcon", { fg = c.gray })
  h(0, "NotifyDEBUGIcon", { fg = c.gray_dark })
  h(0, "NotifyTRACEIcon", { fg = c.gray_dark })
  h(0, "NotifyERRORTitle", { fg = c.gray_lighter, bold = true })
  h(0, "NotifyWARNTitle", { fg = c.gray_light, bold = true })
  h(0, "NotifyINFOTitle", { fg = c.gray, bold = true })
  h(0, "NotifyDEBUGTitle", { fg = c.gray_dark, bold = true })
  h(0, "NotifyTRACETitle", { fg = c.gray_dark, bold = true })

  -- Sniprun
  h(0, "SniprunVirtualTextOk", { fg = c.gray_lighter, bg = c.gray_very_dark })
  h(0, "SniprunFloatingWinOk", { fg = c.gray_lighter, bg = c.gray_very_dark })
  h(0, "SniprunVirtualTextErr", { fg = c.gray, bg = c.gray_very_dark })
  h(0, "SniprunFloatingWinErr", { fg = c.gray, bg = c.gray_very_dark })

  -- Oil (file manager)
  h(0, "OilDir", { fg = c.gray_lighter })
  h(0, "OilDirIcon", { fg = c.gray_light })
  h(0, "OilFile", { fg = c.fg })
  h(0, "OilLink", { fg = c.gray_light, underline = true })
  h(0, "OilLinkTarget", { fg = c.gray, underline = true })
  h(0, "OilCopy", { fg = c.gray })
  h(0, "OilMove", { fg = c.gray })
  h(0, "OilTrash", { fg = c.gray_dark })
  h(0, "OilCreate", { fg = c.gray_lighter })
  h(0, "OilDelete", { fg = c.gray })
  h(0, "OilChange", { fg = c.gray_light })
  h(0, "OilPermissionWrite", { fg = c.gray_light })
  h(0, "OilPermissionRead", { fg = c.gray })
  h(0, "OilPermissionExecute", { fg = c.gray_lighter })
  h(0, "OilPermissionNone", { fg = c.gray_dark })
  h(0, "OilOrphanLink", { fg = c.gray_dark })
  h(0, "OilSocket", { fg = c.gray })
  h(0, "OilPipe", { fg = c.gray })
  h(0, "OilCharDevice", { fg = c.gray })
  h(0, "OilBlockDevice", { fg = c.gray })

  -- Leap / Lightspeed / Hop (additional)
  h(0, "LeapMatch", { fg = c.black, bg = c.white, bold = true })
  h(0, "LeapLabelPrimary", { fg = c.black, bg = c.white, bold = true })
  h(0, "LeapLabelSecondary", { fg = c.black, bg = c.gray_light, bold = true })
  h(0, "LeapLabelSelected", { fg = c.black, bg = c.gray_lighter, bold = true })
  h(0, "LeapBackdrop", { fg = c.gray_dark })

  -- Lualine (if user uses custom lualine theme)
  h(0, "lualine_a_normal", { bg = c.gray_dark, fg = c.white, bold = true })
  h(0, "lualine_a_insert", { bg = c.gray_light, fg = c.black, bold = true })
  h(0, "lualine_a_visual", { bg = c.gray_lighter, fg = c.black, bold = true })
  h(0, "lualine_a_replace", { bg = c.gray, fg = c.black, bold = true })
  h(0, "lualine_a_command", { bg = c.gray_mid, fg = c.black, bold = true })
  h(0, "lualine_a_inactive", { bg = c.gray_very_dark, fg = c.gray, bold = true })
  h(0, "lualine_a_terminal", { bg = c.gray_light, fg = c.black, bold = true })
  h(0, "lualine_b_normal", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "lualine_b_insert", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "lualine_b_visual", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "lualine_b_replace", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "lualine_b_command", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "lualine_b_inactive", { bg = c.black, fg = c.gray })
  h(0, "lualine_b_terminal", { bg = c.gray_very_dark, fg = c.fg })
  h(0, "lualine_c_normal", { bg = c.black, fg = c.gray })
  h(0, "lualine_c_insert", { bg = c.black, fg = c.gray })
  h(0, "lualine_c_visual", { bg = c.black, fg = c.gray })
  h(0, "lualine_c_replace", { bg = c.black, fg = c.gray })
  h(0, "lualine_c_command", { bg = c.black, fg = c.gray })
  h(0, "lualine_c_inactive", { bg = c.black, fg = c.gray_dark })
  h(0, "lualine_c_terminal", { bg = c.black, fg = c.gray })

  -- Define colors_name to register the colorscheme
  vim.g.colors_name = "omarchy-mono"
end

function M.setup()
  setup_highlights()
end

-- Auto-setup when this file is loaded as a colorscheme
if vim and vim.api then
  M.setup()
end

return M